version: '3.7'

services:
  todo-api:
    build:
      context: .
      target: dev
    ports:
     - 3000:3000
    volumes:
     - ./:/app
     - /app/node_modules
     - /app/app
    depends_on:
     - mongo

  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

volumes:
 mongo-db:
